
export default {
    login: '/api/CreateUserToken',
    currentUserInfo: '/api/currentUserInfo',
    CurrentUserBiometriciBind:'/api/CurrentUserBiometriciBind',
    CheckUserBiometricIdentification:'/api/CheckUserBiometricIdentification',
    CurrentUserUnbindBiometric:'/api/CurrentUserUnbindBiometric',
    currentCustomerInfo: '/api/CurrentCustomerInfo',
    currentCustomerSetting: '/api/CurrentCustomerSetting',
    currentUserLogout: '/api/CurrentUserLogout',
    CurrentUserTipsPersonalInformation:'/api/CurrentUserTipsPersonalInformation',
    smsValidateCodeSend: '/api/SmsValidateCodeSend',
    smsValidateCodeCheck: '/api/SmsValidateCodeCheck',
    smsValidateResetPassword: '/api/SmsValidateResetPassword',
    ForgetPasswordRestPassword:'/api/ForgetPasswordRestPassword',
    ForgetPasswordSendEmail: '/api/ForgetPasswordSendEmail',
    QuerySerialNumberByEmail: '/api/QuerySerialNumberByEmail',
    enterpriseRegister: '/api/EnterpriseRegister',
    paymentList: '/api/PaymentList',
    appLastVersion: '/api/AppLastVersion',
    waitMyApproveCount: '/api/WaitMyApproveCount',
    currentUserChangePassword: '/api/CurrentUserChangePassword',
    travelStandards: '/api/TravelStandardsV2',
    currentUserTravellerList: '/api/CurrentUserTravellerList',
    currentUserEmployeeList: '/api/CurrentUserEmployeeList',
    currentUserProjectList: '/api/CurrentUserProjectList',
    customerDictItemList: '/api/CustomerDictItemList',
    customerApproverList: '/api/CustomerApproverList',
    approveInfo: '/api/ApproveInfo',
    getApproverBySetp:'/api/GetApproverBySetp',
    paymentCancel: '/api/PaymentCancel',
    paymentApp: '/api/PaymentApp',
    countrylist: '/api/countrylist',
    paymentInfo: '/api/PaymentInfo',
    CertificateImageUpload: '/api/CertificateImageUpload',
    CurrentDictList: '/api/CurrentDictList',
    CommonArea: '/api/CommonArea',
    CommonCity: '/api/CommonCity',
    CustomerNoticeList: '/api/CustomerNoticeList',
    CurrentUserTravellerRemove: '/api/CurrentUserTravellerRemove',
    CurrentUserTravellerEdit: '/api/CurrentUserTravellerEdit',
    CurrentUserTravellerAdd: '/api/CurrentUserTravellerAdd',
    CurrentUserEmployeeEdit: '/api/CurrentUserEmployeeEdit',
    CurrentUserEditAuthorizedApprove: '/api/CurrentUserEditAuthorizedApprove',
    CreateWorkOrder: '/api/CreateWorkOrder',
    CustomerEmployeeLeaderInfo: '/api/CustomerEmployeeLeaderInfo',
    TravelReportSummyInfo: '/api/TravelReportSummyInfo',
    TravelReportAnalysis: '/api/TravelReportAnalysis',
    TravelReportAnalysisOrders: '/api/TravelReportAnalysisOrders',
    CustomerNoticeADList: '/api/CustomerNoticeADList',
    SmsSendForApp: '/api/SmsSendForApp',
    SmsValidateForApp: '/api/SmsValidateForApp',
    CreateUserTokenForMobile: '/api/CreateUserTokenForMobile',
    CurrentUserBindMobileCaptcha: '/api/CurrentUserBindMobileCaptcha',
    CurrentUserBindMobile: '/api/CurrentUserBindMobile',
    GetAdStrategyContent: "/api/GetAdStrategyContent",
    PaymentWallet: '/api/PaymentWallet',
    CurrentUserMessageSummary: '/api/CurrentUserMessageSummary',
    CurrentUserMessageList: '/api/CurrentUserMessageList',
    CurrentUserMessageRead: '/api/CurrentUserMessageRead',
    CurrentUserMessageBatchRead: '/api/CurrentUserMessageBatchRead',
    CurrentUserMassInfo: '/api/CurrentUserMassInfo',
    CurrentCustomerServiceFees:'/api/CurrentCustomerServiceFees',
    CurrentUserChangeLanguage:'/api/CurrentUserChangeLanguage',
    LanguageSource:'/api/LanguageSource?platform=app',
    HighRiskPC: '/api/HighRisk',
    OrderValidateTravelApply:'/api/OrderValidateTravelApply',
    GetAirLineList:'/api/GetAirLineList',
    HotelGroupList:'/api/HotelGroupList',
    LoginConfig:'/api/LoginConfig',
    OrderFileUpload:'/api/OrderFileUpload',
    OrderHubInvoiceRight:'/api/OrderHubInvoiceRight',
    OrderHubInvoiceList:'/api/OrderHubInvoiceList',
    OrderHubDownloadInvoice:'/api/OrderHubDownloadInvoice',
    TravelApplyUrgeApproval:'/api/TravelApplyUrgeApproval',
    TravelApplyCheckTravelApplyMode:'/api/TravelApplyCheckTravelApplyMode',
    GetCreditCardList:'/api/GetCreditCardList',
    HandShakeCreateCreditCard:'/api/HandShakeCreateCreditCard',
    DeleteCreditCard:'/api/DeleteCreditCard',
    GetCreditCardRaw:'/api/GetCreditCardRaw',
    CommonEnum:'/api/CommonEnum',
    TravelerManagerList:'/api/TravelerManagerList',
    HandShakeDeleteCreditCard:'/api/HandShakeDeleteCreditCard',
    HandShakeGetCreditCardList:'/api/HandShakeGetCreditCardList',
    CreateCreditCard:'/api/CreateCreditCard',
    HandShakeGetCreditCardRaw:'/api/HandShakeGetCreditCardRaw',
    HandShakeEmployeeQuery:'/api/HandShakeEmployeeQuery',
    HandShakeApprove:'/api/HandShakeApprove',
    AnalyzePdfDictionary: '/api/AnalyzePdfDictionary',
    EmployeeQueryForApproveAgent:'/api/EmployeeQueryForApproveAgent',
    PaymentAllList: '/api/PaymentAllList',
    PaymentSerialNumberList: '/api/PaymentSerialNumberList',
    FlightOrderApiPay: '/api/FlightOrderApiPay',
    TrainOrderApiPay: '/api/TrainOrderApiPay',
    CurrentUserMessageChangeStatus: "/api/CurrentUserMessageChangeStatus",
    UpdateCreditCard:"/api/UpdateCreditCard",
    HandShakeUpdateCreditCard:"/api/HandShakeUpdateCreditCard",
    AppPushRegister: '/api/AppPushRegister',
    GetCraftTypeList: '/api/GetCraftTypeList',
    ProfileCommonEnum: '/api/CommonEnum',
    MassOrderTravellerUpdateCheck: '/api/MassOrderTravellerUpdateCheck',
    flight: {
        orderList: '/api/FlightOrderList',
        city_code: '/content/json/city_code.json',
        fltQueryLowPrice: '/api/FltQueryLowPrice',
        fltReissueQuery: '/api/FltReissueQuery',
        flightStopInfo: '/api/FlightStopInfo',
        fltQueryMorePrice: '/api/FltQueryMorePriceV',
        chTravellerRules: '/api/ChTravellerRules',
        chQueryBindProduct: '/api/ChQueryBindProduct',
        newMatchTravelRules: '/api/NewMatchTravelRulesV2',
        fltOrderCreate: '/api/FltOrderCreate',
        flightOrderApproveNotify: '/api/FlightOrderApproveNotify',
        fltOrderCancel: '/api/FltOrderCancel',
        filghtOrderInfo: '/api/FilghtOrderInfo',
        flightOrderRefundPrice: '/api/FlightOrderRefundPrice',
        flightOrderRefund: '/api/FlightOrderRefund',
        flightOrderReschedule: '/api/FlightOrderReschedule',
        paymentList: '/api/PaymentList',
        FlightCityList: '/api/FlightCityList',
        flightOrderMyApproveList: '/api/FlightOrderMyApproveList',
        flightOrderApprove: '/api/FlightOrderApprove',
        addMyBooker:'/api/AddMyBooker',
        RemoveMyBooker:'/api/RemoveMyBooker',
        RequestForWithdraw:'/api/RequestForWithdraw',
        ResubmitHandShakeApprove:'/api/ResubmitHandShakeApprove',
        MyBookerList:'/api/MyBookerList',
        MyTravelerList:'/api/MyTravelerList',
        AddMyNewTraveler:'/api/AddMyNewTraveler',
        RemoveMyTraveler:'/api/RemoveMyTraveler',
        GetElectronicItineraryHeader:'/api/GetElectronicItineraryHeader',
        FlightOrderRefundPrice:'/api/FlightOrderRefundPrice',
        FlightOrderReissueFee:'/api/FlightOrderReissueFee',
        FlightTicketUnUsedList:'/api/FlightTicketUnUsedList',
        FltOrderValidateTicketStatus:'/api/FltOrderValidateTicketStatus',
        OrderPnrSeatInfo:'/api/OrderPnrSeatInfo',
        //查询座位
        OrderSeatMap:'/api/OrderSeatMap',
        //选择座位
        OrderSeatChoose:'/api/OrderSeatChoose',
        //删除座位
        OrderSeatDelete:'/api/OrderSeatDelete',
    },
    train: {
        trainQuery: '/api/TrainQuery',
        GetRecommendedTrainQuery: '/api/GetRecommendedTrainQuery',
        CommonTrainStation2: '/api/CommonTrainStation2',
        orderList: '/api/TrainOrderList',
        trainStopStations2: '/api/TrainStopStations2',
        trainOrderCreate: '/api/TrainOrderCreate',
        TrainPaymentList: '/api/TrainPaymentList',
        TrainOrderApproveNotify2: '/api/TrainOrderApproveNotify2',
        TrainOrderCancel2: '/api/TrainOrderCancel2',
        TrainOrderDetail2: '/api/TrainOrderDetail2',
        TrainOrderRefund2: '/api/TrainOrderRefund2',
        TrainOrderReissue2: '/api/TrainOrderReissue2',
        TrainOrderMyApproveList: '/api/TrainOrderMyApproveList',
        TrainOrderApprove2: '/api/TrainOrderApprove2',
        Train12306ApplyLogin2:'/api/Train12306ApplyLogin2',
        Train12306SmsVerify2:'/api/Train12306SmsVerify2',
        TrainAccountCancelApp:'/api/TrainAccountCancelApp',
        TrainOrderGrabCancel:'/api/TrainOrderGrabCancel',
        Train12306AutoLogin:'/api/Train12306AutoLogin2',
        Train12306LoginCode2:'/api/Train12306LoginCode2', 
        Train12306FaceLogin:'/api/Train12306FaceLogin',
    },
    inflFlight: {
        orderList: '/api/IntlFlightOrderList2',
        CommonAirport2: '/api/CommonAirport2',
        GetCommonAirport2: '/api/GetCommonAirport2',
        IntlFlightQuery: '/api/IntlFlightQuery',
        IntlFlightRules: '/api/IntlFlightRules',
        IntlFlightGetPolicy: '/api/IntlFlightGetPolicy',
        IntlFlightPrice: '/api/IntlFlightPrice',
        IntlOrderCreate: '/api/IntlOrderCreate',
        IntlFlightOrderApproveNotify: '/api/IntlFlightOrderApproveNotify',
        IntlFlightOrderCancel: '/api/IntlFlightOrderCancel',
        IntlFlightOrderDetail: '/api/IntlFlightOrderDetail',
        IntlFlightOrderRefund: '/api/IntlFlightOrderRefund',
        IntlFlightOrderReschedule: '/api/IntlFlightOrderReschedule',
        IntlFlightApproveList: '/api/IntlFlightApproveList',
        IntlFlightOrderApprove: '/api/IntlFlightOrderApprove',
        SsoTest:'/api/SamlSpInitForApp',
        IntlFlightMatchTravelRules:'/api/IntlFlightMatchTravelRules',
        CommonAirline:'/api/CommonAirline2',
        getIntlFlightQueryByPriceI:'/api/IntlFlightQueryByPriceI',
        FlightOrderPnrSeatInfo:'/api/FlightOrderPnrSeatInfo',
        FlightOrderSeatMap:'/api/FlightOrderSeatMap',
        FlightOrderSeatChoose:'/api/FlightOrderSeatChoose',
        //删除座位
        FlightOrderSeatDelete:'/api/FlightOrderSeatDelete',
    },
    hotel: {
        orderList: '/api/HotelOrderList',
        city: '/api/HotelCityList',
        citylist: '/common/citylist',
        HotelListQueryV2: '/api/HotelListQueryV2',
        GetHotelCondition: '/api/GetHotelCondition',
        HotelDetailV2: '/api/HotelDetailV2',
        HotelMatchTravelRulesV2: '/api/HotelMatchTravelRulesV2',
        HotelOrderCreateV2: '/api/HotelOrderCreateV2',
        CreditCardValidate2: '/api/CreditCardValidate2',
        HotelOrderGuaranteeV2: '/api/HotelOrderGuaranteeV2',
        HotelResPaymentCode: '/api/HotelResPaymentCode',
        HotelPaymentConfitm: '/api/HotelPaymentConfitm',
        HotelOrderApproveDetail: '/api/HotelOrderApproveDetail',
        HotelOrderDetail2: '/api/HotelOrderDetail2',
        HotelOrderRefund2: '/api/HotelOrderRefund2',
        HotelOrderCancel2: '/api/HotelOrderCancel2',
        HotelOrderApproveList: '/api/HotelOrderApproveList',
        HotelOrderApprove: '/api/HotelOrderApprove',
        HotelOrderPayment: '/api/HotelOrderPaymentInfo',
        HotelOrderRefundPayInfo:'/api/HotelOrderRefundPayInfo',
        HotelCityFilters: '/api/HotelCityFilters',
        HotelBrand: '/api/HotelBrand',
        HotelOrderComputeRefundFee: '/api/HotelOrderComputeRefundFee',
        CityLocationQuery:'/api/CityLocationQuery',
        HotelKeywordQuery:'/api/HotelKeywordQuery',
        HotelSalfChooseApprovalOrSelfPay:'/api/HotelSalfChooseApprovalOrSelfPay',
        HotelApplyTravelRule:'/api/HotelApplyTravelRule',
        HotelOrderRatePlanPriceCheck:'/api/HotelOrderRatePlanPriceCheck',
        HotelOrderApproveNotify:'/api/HotelOrderApproveNotify',
        HotelCreditCVVSubmit:'/api/HotelCreditCVVSubmit',
        HotelOrderPoiQuery: '/api/HotelOrderPoiQuery',
    },
    intlHotel: {
        orderList: '/api/ForeignHotelorderList',
        ForeignHotelCityList: '/api/ForeignHotelCityList',
        ForeignHotelList: '/api/ForeignHotelList',
        ForeignHotelDetail: '/api/ForeignHotelDetail',
        ForeignHotelOrderCreate: '/api/ForeignHotelOrderCreate',
        ForeignHotelorderList: '/api/ForeignHotelorderList',
        ForeignHotelOrderDetail: '/api/ForeignHotelOrderDetail',
        ForeignHotelCancelOrder: '/api/ForeignHotelCancelOrder'
    },
    invoice: {
        currentUserTravellerInvoiceList: '/api/CurrentUserTravellerInvoiceList',
        deleteCustomerEmployeeInvoice: '/api/DeleteCustomerEmployeeInvoice',
        customerEmployeeInvoiceSave: '/api/CustomerEmployeeInvoiceSave',
        currentUserTravellerAddressList: '/api/CurrentUserTravellerAddressList',
        deleteEmployeeAddress: '/api/DeleteEmployeeAddress',
        employeeAddressSave: '/api/EmployeeAddressSave',
        GetOrderBatchInvoiceMailing: '/api/GetOrderBatchInvoiceMailing',
        GetSingleOrderBatchInvoiceMailing: '/api/GetSingleOrderBatchInvoiceMailing',
        InvoicedOrderList: '/api/InvoicedOrderList',
        CancelInvoiceOrder: '/api/CancelInvoiceOrder',
        InvoiceOrderPaymentInfo: '/api/InvoiceOrderPaymentInfo',
        InvoicingFlightOrderList: '/api/InvoicingFlightOrderList',
        InvoicedOrderDetail: '/api/InvoicedOrderDetail',
        InvoiceContent: '/api/InvoiceContent',
        CreateInvoiceOrder: '/api/CreateInvoiceOrder'
    },
    application: {
        travelApplyList: '/api/TravelApplyList',
        TravelApplyItem: '/api/TravelApplyItem',
        TravelApplyCancel: '/api/TravelApplyCancel',
        SubjectType: '/api/SubjectType',
        TravelApplyApprovalDetail: '/api/TravelApplyApprovalDetail',
        TravelApplyCreate: '/api/TravelApplyCreate',
        TravelApplyApprovalList: '/api/TravelApplyApprovalList',
        TravelApplyApprove: '/api/TravelApplyApprove',
        TravelApplyFileUpload: '/api/TravelApplyFileUpload',
        TravelApplyWithdrawnApproval:'/api/TravelApplyWithdrawnApproval',
        TravelApplyCheckTravelApplyMode:'/api/TravelApplyCheckTravelApplyMode',
    },
    mice: {
        MiceDemandCreateOrder: '/api/MiceDemandCreateOrder',
        MiceDemandChangeStatus: '/api/MiceDemandChangeStatus',
        MiceDemandDetail: '/api/MiceDemandDetail',
        MiceDemandList: '/api/MiceDemandList',
        MiceDemandNotify: '/api/MiceDemandNotify',

    },
    car: {
        airport_coordinate: '/Content/json/airport_coordinate.json',
        CarPrice: '/api/CarPrice',
        car_policy: '/Content/json/car_policy.json',
        CreateCarOrder: '/api/CreateCarOrder',
        CarOrderList: '/api/CarOrderList',
        CarDetail: '/api/CarDetail',
        CarCancel: '/api/CarCancel',
        CarCancelConfirm: '/api/CarCancelConfirm',
        CarSzzcNearbyCarInfo: '/api/CarSzzcNearbyCarInfo',
        CarSzzcEstimationPrice: '/api/CarSzzcEstimationPrice',
        CarSzzcCityService: '/api/CarSzzcCityService',
        CarSzzcCreateOrder: '/api/CarSzzcCreateOrder',
        CarSzzcOrderRealTime: '/api/CarSzzcOrderRealTime',
        CarSzzcCancelReason: '/api/CarSzzcCancelReason',
        CarSzzcCancelOrder: '/api/CarSzzcCancelOrder',
        CarOrderCancelReason: '/api/CarOrderCancelReason',
    },
    account: {
        CustomerEmployeeLedgerList: "/api/CustomerEmployeeLedgerList",
        CustomerEmployeeLedgerCancel: '/Api/CustomerEmployeeLedgerCancel',
        LedgerCategoryList: "/Api/LedgerCategoryList",
        CustomerEmployeeLedgerAdd: '/api/CustomerEmployeeLedgerAdd',
        LedgerCategoryAdd: '/Api/LedgerCategoryAdd',
        CustomerEmployeeLedgerStatistics: "/Api/CustomerEmployeeLedgerStatistics"
    },
    reimbursement: {
        ReimbursementList: '/api/ReimbursementList',
        ReimbursementBindList: '/api/ReimbursementBindList',
        GetEmployeeCollectionList: '/api/GetEmployeeCollectionList',
        ReimbursementDetail: '/api/ReimbursementDetail',
        ReimbursementApprovalList: '/api/ReimbursementApprovalList',
        ReimbursementApprove: '/api/ReimbursementApprove',
        ReimbursementCreate: '/api/ReimbursementCreate',
        ReimbursementRevoke: '/api/ReimbursementRevoke'
    },
    /**企业订单列表 */
    enterpriseOrder: {
        flightOrders: '/api/admin/flightOrders',
        intlFlightOrders:'/api/admin/intlFlightOrders',
        hotelOrders:'/api/admin/hotelOrders',
        foreignHotelOrders:'/api/admin/foreignHotelOrders',
        trainOrders:'/api/admin/trainOrders',
        carOrders:'/api/admin/carOrders',
        miceOrders:'/api/admin/miceList',
    },
    enterpriseOrderDetail: {
        flightOrderDetail:'/api/admin/flightOrderDetail',
        intlFlightOrderDetail:'/api/admin/intlFlightOrderDetail',
        hotelOrderDetail:'/api/admin/hotelOrderDetail',
        foreignHotelOrderDetail:'/api/admin/foreignHotelOrderDetail',
        trainOrderDetail:'/api/admin/trainOrderDetail',
        carOrderDetail:'/api/admin/carOrderDetail',
        miceDetail:'/api/admin/miceDetail'

    },
    enterprisePerson: {
        accountExecutive: '/api/admin/accountExecutive',
        customerManagerList:'/api/admin/customerManagerList',
        customerManagerOperate:'/api/admin/customerManagerOperate',
        customerContract:'/api/admin/customerContract'
    },
    enterpriseParment:{
        customerStructure: '/api/admin/customerStructure',
        deptSave: '/api/admin/deptSave',
        settlementSubjectQuery:'/api/admin/settlementSubjectQuery',
        deptDetail:"/api/admin/deptDetail",
        employeeDetail:"/api/admin/employeeDetail",
        commonQuery:"/api/admin/commonQuery",
        customerDepartmentQuery:"/api/admin/customerDepartmentQuery",
        dutyQuery:"/api/admin/dutyQuery",
        travelRulesQuery:"/api/admin/travelRulesQuery",
        airLineQuery:'/api/admin/airLineQuery',
        employeeSave:'/api/admin/employeeSave',
        employeeUpdateDept:'/api/admin/employeeUpdateDept',
    },
    /**
     * 综合订单列表
     */
    comprehensive: {
        MassOrderQueryTravellers:'/api/MassOrderQueryTravellers',
        MassOrderCheckTravellers:'/api/MassOrderCheckTravellers',
        MassOrderCreate:'/api/MassOrderCreate',
        MassOrderSubmit:'/api/MassOrderSubmit',
        MassOrderList:'/api/MassOrderList',
        MassOrderDeleteOrderItem:'/api/MassOrderDeleteOrderItem',
        MassOrderCancel:'/api/MassOrderCancel',
        MassOrderDetail:'/api/MassOrderDetail',
        MassOrderApprovalRepush:'/api/MassOrderApprovalRepush',
        MassOrderWithdrawnApproval:'/api/MassOrderWithdrawnApproval',
        MassOrderApprove2:'/api/MassOrderApprove2',
        RecentNotTravelOrders:'/api/RecentNotTravelOrders',
    }

}