export default {
    '付费':'Payment service',
    '楼层':'floor',
    '所属渠道：':'channel',
    '订单通知':'Orders Information',
    '经济舱':'Economy Class',
    '商务舱/公务舱':'Business Class',
    '头等舱':'First Class',
    '小食':'Snacks',
    '热食':'Hot Food',
    '午餐':'Luncher',
    '茶点':'Refreshment',
    '正餐':'Dinner',
    '冷餐':'Buffet',
    '香港':'HongKong',
    '台湾':'TaiWan',
    '澳门':'Macao',
    '巴黎':'Paris',
    '伦敦':'London',
    '罗马':'ROM',
    '日本':'Tokyo',
    '首尔':'Seoul',
    '东京':'Tokyo',
    '迪拜':'Dubai',
    '台北':'Taipei',
    '洛杉矶':'Los Angeles',
    '纽约':'New York',
    '曼谷':'Bangkok',
    '信用卡担保':'Credit card',
    '到店付款':'Pay on Arrival',
    '限时取消':'Time limited cancellation',
    '退订总额:':'Unsubscribe',
    '免费':'Free',
    '行李额':'Baggage Allowance',
    '折扣限制':'Discount limit',
    "因任何原因需要进行的退改签机票（包含因客观原因导致的航班取消），须自行通过订票系统或拨打{{noun}}进行退改签操作处理": "For ticket changes or cancellations (including those due to involuntary flight disruptions), please process them via our platform or call {{noun}}",
    "返程":"Return",
    "更多舱位":"More cabins",
    '根据贵公司差旅政策规定，您未选择经济舱{{noun}}折以内航班，故请您选择原因:':'Base on th travel policy of your company, you should book the flight within {{noun}} economy class ',
    "证件号：":"Number:",
    "评分来自各大平台平均分数":"The score comes from the platform average",
    // "1、该酒店确认后按照取消规则取消，可能扣除一定的费用；订单需等酒店或供应商确认后生效，订单确认结果以短信或邮件通知为准，如订单不确认将全额退款至你的付款账户。\n2、该订单不向个人提供发票，员工无需在酒店获取发票及消费明细，由公司统一结算。":"1. Subject to the hotel's terms and conditions, applicable fee shall be chagreable for the cancellation of the confirmed reservation. The booking reservation must be confirmed by the hotels or service providers with the notification received from FCM via SMS or email.Should there be no confirmation received, a full refund shall be returned to your account base on the original payment method of your payment. \n2. No invoice (Fapiao) is provided to individual for this booking order. Employees do not need to obtain invoice (Fapiao) or itemized expenditure statement from the hotel. Hotel billing will be settled by the company.",
    "每个房间只需要填写1位入住人，如有同住人请点击“新增入住人”（同住人仅在账单中展示）,酒店办理入住时需提供第一位入住人的身份信息，所填姓名与入住时所持证件的姓名一致，否则酒店有权拒绝为您办理入住。":"Only one person needs to be filled in each room. If there is a roommate, please click 'new roommate' (roommate is only shown in the bill)",
    "当天酒店已全部预定，请选择其他日期或者酒店": "Hotel room has been sold out , please choose other rooms or hotels",
    "到店付需员工到酒店前台个人支付，房费到店付款，FCM不提供发票，如需消费凭证，请向酒店前台索取消费清单。": "Employees are required to pay at the hotel front desk upon check-in.Room charges must be settled directly at the hotel.FCM does not provide invoices / Fapiao. If a receipt is required, please request an invoice statement from the hotel front desk.",
    "酒店设施服务":"Facilities Service",
    "开业时间：":"Opening date：",
    "酒店相册":"Hotel photo album",
    "请选择未预订符合星级酒店的原因":'Please select the reason for not booking a star rated hotel',
    "暂无评论":"No comments",
    "本次预订使用{{noun}}的差旅标准":"The travel policy of {{noun}} is used for this reservation",
    "费用信息":"Cost information",
    "太平洋保险":"Pacific Insurance Agency",
    "持卡人证件号":"ID number of cardholder",
    "住{{noun}}间":'Book{{noun}}room',
    "二星": "Two star",
    "商圈":"Business District",
    "机场/车站":"Airport/Station",
    "医院":"Hospital",
    "市内景点":"City Attractions",
    "市外景点":"Out-of-town Attractions",
    "大学":"University",
    "演出场馆":"Venue",
    "购物中心":"Shopping Center",
    "品牌":"Brand",
    "办公室地址": "Company Locations",
    '温馨提示：请确保您提供的信息与发卡行记录的信息一致': 'NOTE: Please provide you credit card information that match your credit card record',
    "违反指定折扣的原因：":'Out-of-policy Reasons:',
    "证件有效期":'Expiration Date of the Certificate',
    "国家地区":"Country / region",
    "FCM是世界最大的商旅管理公司之一，我们的全天候服务运营网络覆盖全球约100个国家及地区，旗下的专业团队遍布各地。FCM也是澳交所上市公司Flight Centre Travel Group（FCTG）的全球旗舰差旅分支机构，拥有丰富的航司、酒店、地面交通等全球资源。无论您身在何地，都能获取专属于您的最佳差旅解决方案。成千上万的全球大型企业和跨国机构，包括众多家喻户晓的品牌、财富与富时100强企业，都信赖FCM的技术与专家团队助其轻松无忧踏上旅程，实现差旅投资回报最大化。":
    "FCM is one of the largest global business travel management companies with a 24/7 worldwide reach in almost 100 countries – so when we say global network, we mean it. The flagship business division of the ASX-listed Flight Centre Travel Group (FCTG), FCM has the leverage to deliver access to the widest worldwide network of airfares, hotels and ground transport for unique and best-value travel solutions. Thousands of national and multi-national organisations around the world, including many household brands, Fortune and FTSE 100 companies, rely on FCM’s intuitive technology and expert teams to move their business travellers effortlessly and maximise their return on investment.",
    "FCM的敏捷、可定制化商旅技术平台能够预测并满足不同企业的需求。我们全球联网的专家团队拥有卓越的协商能力、丰富的当地行业经验，为您的商旅人员提供差旅安全照管支持，让企业尽享非凡的个性¬化商旅体验。无论您是定期去往国外出差，还是临时决定出行，或是想要整合多个国家间的差旅服务，FCM是您值得信赖的商旅合作伙伴。":
    "FCM’s agile and customisable travel technology platform anticipates and solves the needs of each business. Our flexible, globally connected teams are experts in negotiating the best deals for their clients, and offer in-depth local knowledge and duty of care support to provide the ultimate personalised business travel experience. FCM is a trusted travel partner for businesses that have regular international travel needs, take single trips at the last-minute, or have centralised their business travel across multiple markets. Discover the alternative at www.fcmtravel.com",
    "工号/手机号":"Job number/Mobile number",
    '请输入登录账号': 'Please enter your login account',
    "新建差旅报销申请":'Create New Travel expense reimbursement application',
    "差旅报销申请详情":"The Order of Travel expense reimbursement application",
    "未选择指定折扣舱位":'Specify the reason',
    "邮箱(必填)":"Email(Required)",
    "邮箱(必填)":"Email(Optional)",
    "维萨卡(Visa)":"Visa",
    "万事达卡(Maestro MA MasterCard)":"Maestro MA MasterCard",
    "万事达卡(Master Card)":"Maestro MA MasterCard",
    "日财卡(Japanese Credit Bureau Credit Card)":"Japanese Credit Bureau Credit Card",
    "美国运通卡(American Express)":"American Express",
    "蓝卡(Carte Bleue)":"Carte Bleue",
    "大莱卡(Diners Club)":"Diners Club",
    "发现卡(Discover Card)":"Discover Card",
    "欧洲信用卡(Eurocard)":"Eurocard",
    "通用航空旅行卡(Universal Air Travel Card)":"Universal Air Travel Card",
    "中国银联卡(China Union Pay Card)":"China Union Pay Card",
    "综合订单":"Bundled Orders",
    "综合订单详情":"Details of the bundled orders",
    "为本人预订":"Reservation for yourself",
    "为员工预订":"Reservation for employee ",
    "预订业务":"Please select the reservation",
    "姓氏(选填)":"First name (optional)",
    "名(选填)":"Last name (optional)",
    "预订人":'Booking Person',
    "创建时间":'Create Time',
    "预订方式":"Book Method",
    "总金额":"Total Amount",
    "火车票信息":"Train Ticket Information",
    "机票信息":"Flights Information",
    "已审批": "Finished Approval",
    "违反政策":"Out-of-policy",
    "联系人信息":"Information of Contact Person",
    "入店":'In the Hotel',
    "入店":'Check in',
    "国内酒店信息":"Hotel Information",
    "港澳台及国际酒店信息":"International Hotel Information",
    "通过": "Agree",
    "记账订单":'Bookkeeping Spreadsheet',
    "个人设置":"Setting",
    "撤回成功":"The withdrawal was successful",
    "差旅报销单详情":"Detail",
    "新建收款账户":'Create New Collection account',
    "请输入{{noun}}金额":'{{noun}} Amount',
    '欢迎使用我们的服务。请阅读并同意下方协议:': 'Welcome to our service. Please read and agree to the following agreements:',
    '继续预订酒店':'Add Hotel',
    "酒店已订完 建议您更改入住时间或选择其他酒店": "The hotel has been fully booked. We recommend that you change your check-in time or choose another hotel.",
    '统一支付':"On account",
    '到店支付':'Pay on arrival',
    '不限':'All',
    "大床":'Double Bed',
    "双床":"Twin Beds",
    "担保":"Guaranteed",
    "到店现付":"Pay on arrival",
    "已关联":"Signed-in",
    "切换":"Switch",
    '已关联/切换':'Signed-in/Switch account',
    '已关联...':'Signed-in...',
    '重新关联':'Re Signed-in',
    '关联中...':'Signed-in...',
    '关联中':'Signed-in',
    '切换/退出12306':'Re associate switch / exit 12306',
    '用户名':'user name',
    '以下':'below',
    '国内酒店订单': "Domestic Hotel Order",
    '以下':'below',
    '港澳台及国际机票信息':'Hongkong,Macau,Taiwan and International Flights Information',
    '未查到直飞航班':'There is no Non-stop flights',
    '同意并继续':'Agree',
    '年龄':'Age',
    "隐私政策": "Privacy Policy",
    '(选填)酒店名/地标/商圈':'(Optional) Hotel name / landmark / business district',
    '点击查看':'Click to View',
    '住': 'Book',
    '很抱歉，没有符合条件的酒店':'No hotel that matches requirements',
    '大床房':'Big types',
    '双床房':'Twin',
    "您尚未绑定手机号": "You haven't link your mobile phone number",
    '暂不绑定': "Temporarily not",
    '绑定手机号':'Binding mobile phone',
    '12306用户名/邮箱/手机号':"12306 user name / email / mobile ",
    '密   码':'password',
    '12306密码，非FCM账号密码':'12306 password, non FCM account password',
    '核验码':'Verification code',
    '发送短信666到12306获取':'Send SMS 666 to 12306 for',
    '记住账号密码':'Remember the account password',
    '登录12306':'Login 12306',
    '退出账号':'Exit account',
    '关联':'relation',
    '铁路局规定购票必须实名制':'The Railway Bureau stipulates that tickets must be purchased under the real name system',
    '登录12306账号提高出票成功率':'Log in to 12306 account to improve the success rate of ticket issuance',
    '飞机票':'Flights',
    '订 完':'Finished Booking',
    "预订政策":'Terms and conditions for booking',
    '没有定位权限不能使用用车功能':'Car service is not available without location authorization',
    "《隐私政策》": "《Privacy Policy》",
    "《FCM服务协议》": "《FCM Service Policy》",
    '勾选并同意': 'Sign in for consent',
    "获取用户信息中，请稍等":"Getting user information...",
    '选择':'Choose',
    '部分无窗':'some',
    '没有符合您查询条件的内容':'No results found',
    "请选择出发地":'select departure city',
    "请选择目的地":'select destination city',
    '出发地':'Departure',
    '目的地':'Destination',
    '请输入手机号':'Please enter your mobile phone number',
    '易宝支付':'YeePay',
    '附件':'annex',
    '目的地城市':'Destination city',
    '已售完':'Sold out',
    '《儿童个人信息保护政策》':"《Children`s Information Protection Policy》",
    '没有可用舱位，请选择其他舱位':"No space available, please select another space",
    '关联12306':"Associated with 12306 account",
    '暂不关联':'Unrelated',
    '请确保12306账号和密码的有效性，否则可能导致出票失败。':'Please ensure the validity of 12306 account and password, otherwise it may lead to ticket failure.',
    '港澳通行证':'Exit-Entry Permit to Hong Kong and Macau',
    '大陆居民往来台湾通行证':'Mainland Resident Travel Permit to Taiwan',
    "外交部签发的驻华外交人员证": "Diplomatic Certificate by Ministry of Foreign Affairs ",
    '民航局规定的其他有效乘机身份证件':'Other travel documents approved by CAA',
    '是否继续提交':'Continue submitting',
    '个性化推荐':'Turn off ad',
    '开':'On',
    '关':'Off',
    '高危区域，不能预订':"It's not allowed to book due to it's the High Risk Area",
    '单点登录':'SINGLE SIGN-ON',
    '欢迎':'Welcome',
    '请输入企业邮箱':'Please,type your work email and continue',
    '请选择未提前预定酒店的原因':'Please select the reason for not booking the hotel in advance',
    "确定同意该订单吗？": "confirm to approve?",
    "输入名称": "Please enter the name",
    "账号错误": "Please enter the correct Email",
    '订票单': 'Ticketed',
    '改签单': 'Exchanged',
    '退票单': 'Refund',
    "催审": "Remind",
    "已阅读上述提示": "I have read the notice above.",
    "星级排序": "Hotel Rating",
    "符合差标": "In policy",
    "专享协议": "Corporate agreement",
    "违反差标": "Out of policy",
    "经停": "Transit via",
    "完成": "Confirm",
    "请输入中文姓名，非持有中国大陆居民身份证件请按照旅行证件上的输入，英文姓名录入格式为":"If you are not a Chinese Mainland Resident, please input your name format as LastName/FirstName as in the travel documentation, use "/" as the separator.",
    "请输入您的英文姓，与旅行证件上保持一致":"Please input your Last / Family name as in the travel documentation",
    "请输入您的英文名，与旅行证件上保持一致":"Please input your First / Given name as in the travel documentation",
    "即时确认":"Instant confirmation",
    "需要申请":"Request needed",
    "已满房":"No Rooms Available",
    "现付酒店":"Post pay hotel",
    "预付酒店":"Pre pay hotel",
    "身份证":"Chinese ID Card",
    "海员证":"Seaman's Book",
    "外国人永久居留身份证":"Foreigner's Permanent Residence ID Card",
    "外国人出入境证":"Foreigner's Exit-Entry Permit",
    "港澳通行证（含电子港澳通行证）":"Exit-Entry Permit for travelling to and from Hong Kong and Macao",
    "军官证":"Military ID",
    "学生证（十六周岁以下）":"Student's ID Card (Uner 16 yrs old)",
    '英文名': 'First name',
    "英文姓": "Last name",
    "确定":"Confirm",
    "取消":"Cancel",
    "手机号重置": "Reset via Mobile",
    "邮箱重置": "Reset via Email",
    "请输入账号": "Please input user name",
    "请输入邮箱": "Please input email",
    "验证码已发送至邮箱，请注意查收！": "Verification Code is sent to your email, please check!",
    "酒店会员卡": "member card",
    "请输入酒店会员卡": "Please select member card number",
    "注意：请使用带有银联标记的信用卡": "Reminder: Please use credit card bearing the UnionPay logo",
    '选择国家/地区': 'Select country',
    '国籍/地区': 'Nationality/Area',
    '请填写国籍/地区': 'Please fill in the nationality',
    '{{noun}}的国籍/地区未填': 'The nationality of {{noun}} has not yet been filled',
    '请选择国籍/地区': 'Please select nationality',
    '是否下载文件？':'Do you want to download the file?',
    "最多只能上传5个文件": "A maximum of 5 files can be uploaded",
    "文件过大，请上传5MB以内的文件": "File is too large， please upload files within 5MB",
    "1、信用卡担保可能会被刷取预授权；使用外币卡被刷预授权可能会产生手续费及汇率差。": "1.Pre-Authorization Details\n A credit card guarantee may involve a pre-authorization charge.If using a foreign currency credit card, pre-authorization may incur fees and exchange rate may vary.",
    "2、请根据酒店要求进行担保，是否担保成功以酒店确认为准。": "2.Guarantee Requirements\nPlease follow the hotel’s requirements for credit card guarantees.Please take hotel’s confirmation as if guarantee is successful or not. ",
    "3、如收到需担保的短信和邮件，请尽快进行担保，否则可能会导致无房。": "3.Timeliness of Guarantee\nIf you receive an SMS or email requesting a guarantee, please complete it promptly.Failure to provide a timely guarantee may result in room cancellation.",
    "预授权通常会涉及冻结一定金额的资金，直到交易完成或取消。这种方式可以帮助保护商家免受欺诈和付款问题的影响，并为持卡人提供更安全的交易保障。": "Pre-authorization typically freezes a certain amount of funds until the transaction is completed or cancelled.This process helps protect merchants from fraud and payment issues while ensuring safer transactions for cardholders.",
    "订单尚未完成，请点击“提交订单”进入下一步。如本酒店行程要求信用卡担保，请注意查收系统发出的担保邮件及短信，并根据指引完成担保。":'Your booking has not been completed yet, please continue to submit the booking. If this hotel booking requires credit card guarantee, please pay attention to the guaranteed emails and text messages and complete the guarantee accordingly.',
    "出差单 ":"Travel request",
    '出差申请': 'Travel request',
    "*具体费用按航空公司官网规定收取": "*Fees is varied by airline. Please refer to Airlines websites for detailed policies.",
    "添加酒店行程":"Add hotel",
    "订单尚未完成，请选择继续添加其他行程或点击提交订单进入下一步。": 'Your booking has not been completed yet, please click the bottom by choosing "add hotel" or "confirm booking" into the next step.',
    "订单已成功撤回审批。":'Booking has been withdrawn succesfully.',
    "以酒店确认为准":"Subject to hotel confirmation",
    "撤回审批":"Withdrawn approval",
    "申请单已成功撤回。":"Travel request has been withdrawn successfully",
    '选择出差人': 'Select employees',
    '选择出差员工': 'Booking on behalf of employees',
    '取消申请':'Cancel Request',
    '预定人所属公司订单模式与所选出差人的公司订单模式不一致，请联系差旅顾问协助，谢谢。':'The booking mode of the booker and the selected traveler is different.Please contact the travel consultant for assistance.Thank you.',
    '请阅读并勾选同意《个人信息跨境传输同意函》':'Please read and agreed《Consent Letter for Cross-border Transfer of Personal Information》',
    '在个人信用卡中维护信用卡信息即认为您认知并同意如下事宜:':'Maintaining credit card information in the Credit Card feature, you acknowledge and agree to:',
    '我们收集您的信用卡号、信用卡到期日等个人敏感信息仅用于实现您的酒店预定担保用途，维护在您的个人资料中的信用卡卡号、信用卡类型、信用卡到期日等数据按照支付卡行业数据安全标准（PCI-DSS）存储和传输。为了您的财产安全，请您妥善保管个人账号和密码，建议每三个月更换密码。如您对此有疑问，请联系我们。':'We collect sensitive personal information such as your credit card Primary Account Number (PAN) and Expiration Date only for the purpose of guaranteeing your hotel reservation. The credit card Primary Account Number (PAN), credit card type, and Expiration Date maintained in your profile is stored and transmitted following payment card industry data security standards (PCI DSS). For the safety of your property, please keep your account and password secure properly -- It is highly recommended to change your password every three months. If you have any questions, please contact us.',
    '个人信用卡':'My Credit Card',
    "信用卡添加成功": "Add success",
    "信用卡号": "Card No.",
    "未找到维护的信用卡":"No credit card found",
    "维护的信用卡类型与酒店担保支持信用卡类型不符":"No credit card type matches with the hotel guarantee required",
    '提交订单': 'Submit Order',
    '您提交的酒店订单：[{{noun1}}]，[{{noun2}}] [{{noun3}}]，请按照如下指引完善担保信息，谢谢！已向您的担保银行预留手机号（尾号为{{noun4}}）发送了验证码，验证码有效期5分钟，未提交验证码将会导致酒店预定失败。':'The hotel order you have submitted: [{{noun1}}], [{{noun2}}] [{{noun3}}], please follow the following guidelines to complete the guarantee, thank you! The verification code has been sent to the mobile phone number (ended with {{noun4}}) registered at the bank, the verification code will be expired in 5 minutes. Please fill in the verification code received and submit it in time, or else the room reservation may fail.',
    '您提交的酒店订单：[{{noun1}}]，[{{noun2}}] [{{noun3}}]，请按照如下指引完善担保信息，谢谢！':'The hotel order you have submitted: [{{noun1}}], [{{noun2}}] [{{noun3}}], please follow the following guidelines to complete the guarantee, thank you!',
    '请确保您提供的信用卡信息正确，如信用卡不符合要求，可能会导致房间担保失败；手工填写的信用卡不会被保存，您可在个人信用卡中维护；':'Please ensure the credit card information is accurate otherwise it may cause the rejection and failure to room guarantee if the credit card information fails to meet the requirements. The credit card input for the guarantee will not be auto saved. It can be maintained in credit card functionality.',
    '注意事项：':'Please Note:',
    '提交验证码':'Fill in the Verification Code',
    '重新获取验证码':'Re-apply the Verficiation Code',
    '短信验证码：':'Verification code',
    '请输入短信验证码':'Verification code',
    '信用卡担保短信核验':'SMS verification',
    '根据供应商要求，本房型担保证件类型仅支持身份证。':'Only resident identification card can be used as credential according to the requests from supplier.',
    '操作过于频繁，请五分钟后重试':'Operation too frequent! Please try again in five minutes.',
    '下载中......':'Downloading',
    '检查更新失败，请稍后重试':'Check for updates failed. Please try again later.',
    '已是最新版本':'You are already on the latest version.',
    '我的订单':'My Orders',
    '发现新版本是否更新':'New Version is available for update',
    '立即更新':'Update',
    '综合订单提交成功':'Reservation Successful',
    '每间':'Number of persons per room',
    '大客户协议':'corp',
    '人脸核验':'facial verification',
    '发送短信息':'send SMS',
    "(已登录)": "(Logged in)",
    "请填写核验码":"Please enter verification code",
    "退出12306":"Exit 12306",
    "账号登录/":"User Login/",
    '/Face ID 登录':"/Face ID Login",
    "/指纹登录":"/Fingerprint Login",
    "下次不再提醒":"Don't notice again",
    "开启":'Turn on',
    "确定关闭吗？": "Confirm to turn off",
    "你可以开启指纹登录，后续登录更便捷": "You can enable Fingerprint login for a more secure and convenient login",
    "你可以开启人脸识别登录，后续登录更便捷": "You can enable FaceId login for a more secure and convenient login",
    "指纹识别登录开启成功": "Fingerprint Login enabled successfully",
    "人脸识别登录开启成功": "FaceId Login enabled successfully",
    "生物识别未注册":'Biometrics not supported',
    "该车次车票未开售": "The train ticket is not on sale",
    '指纹登录失败，请稍后重试或者切换其他登录方式登录':'Fingerprint login failed, please try again later or switch with other logins',
    '人脸登录失败，请稍后重试或者切换其他登录方式登录':'FaceID login failed, please try again later or switch with other logins',
    '设备未开启或不支持生物识别登录':'Equipment stays closed or do not support with biometric sign-in',
    '申请已提交，实际费用以最终航司确认为准':'Your request has been submitted, the actual cost is subject to the final confirmation of the Airline.',
    '您正指定{{noun}},成为您的差旅预定人，如您继续下一步且预定人接受申请，您指定的预定人可为您进行差旅预定，并维护您包括证件号和信用卡号在内的个人信息。':'You are now assigning {{noun}}, as your travel arranger, if you proceed and the travel arranger agrees, the travel arranger you assigned will be able to make booking and maintain your information (including ID numbers and cardholder data) for you.',    "添加成功": "Add success",
    "邮箱：":"Email: ",
    "登录12306账号":"Login 12306",
    "发票抬头名称": "Invoice Header",
    "验证码登录":"Verification code login",
    "立即登录":"Sign in now",
    "请输入密码": "Login password",
    "忘记密码": "Forgot password?",
    "发送验证码": "Get verification code",
    "- 其他登录方式 -":"- Other login methods -",
    "欢迎探索非凡之旅":"Discover the alternative",
    '请输入绑定手机号':'Please enter your mobile phone number',
    "我已阅读并同意":"Please confirm you have read and agree to",
    "我同意":"Please confirm you have read and agree to",
    "预订人员：{{noun}}":"Reservation officer: {{noun}}",
    "差标及审批流": "Policy and Approval Workflow",
    "订单号：{{noun}}":"Order No. {{noun}}",
    "*退改签以航司最终确认为准":"*Final confirmation is subject to the Airline",
    "《FCM儿童个人信息保护政策及监护人须知》": "《FCM Children’s Personal Information Protection Policy and Guardian’s Notice》",
    "《FCM个人信息保护政策》":"《FCM Personal Information Protection Policy》",
    '\n    本次改期费共{{noun1}}元，含票面差价{{noun2}}元及改期手续费/税差{{noun3}}元':'Total amount CNY({{noun1}}), including Fare Difference CNY({{noun2}}) and Change Fee and Tax CNY({{noun3}})',
    '\n   *因价格实时变动，最终具体金额以航司确认为准。':"\n   *Due to the price changes from time to time, the final amount is subject to airline's confirmation",
    '    因选择航班运价不同，优享权益会有变化，请以最终确认为准':"  The privileged benefits may change due to different flights. Final confirmation is subject to the airline.",
    "预 订": "Book",
    '(未完成)':'(In Progress)',

    "退改规则": "Fare Rules",
    '行李说明': 'Baggage',
    "港澳台及国际酒店":"HK, MO, TW and INT Hotel",
    "港澳台及国际机票":"HK, MO, TW and INT Flight",
    "符合城市标准":'Applied to City Cap',
    "点击提交订单表示您已阅读并同意":"By submitting your order, you confirm acceptance of",
    "以上条款":"The above terms",
    
    "《个人信息跨境传输同意函》": "《Consent Letter for Cross-border Transfer of Personal Information》",
    "《服务协议》": "《Terms of Services》",
    "出差人:": "Traveler:",
    "服务协议和隐私政策": 'Terms of Services and Privacy policy',
    "单个文件最大5MB，数量最多5个，格式为:": "Single file maximum 5MB, up to 5 files, format:",
    "近期行程": "Recent Trip",
    "新建订单": "New Order",
    "选择出差人": "Select traveler",
    "选择出差单": "Select travel request",
    "选择出行人": "Select traveler",
    "选择预订业务": "Select booking",
    "查看全部订单": "View all orders",
    "航空保险": "Aviation Insurance",
    "电子行程单（如发票信息开错，请联系您的差旅顾问）": "Electronic Itinerary (if the invoice information is wrong, please contact your travel consultant)",
    "电子行程单": "Electronic Itinerary",
    "超标内容": "Over-size content",
    "根据贵公司差旅政策规定，您未选择最低价舱位航班，故请您选择原因:": "Only lowest fare is allowed according to company travel policy. Please choose out-of-policy reasons.",
    "符合": "In Policy",
    "违反": "Out of Policy",
    "出差行程": "Travel Request",
    "机票查询": "Flight Search",
    "酒店查询": "Hotel Search",
    "不限舱位": "Any Cabin",
    "近期查询": "Recent Search",
    "清除": "Clear",
    "请选择出差人": "Please select traveler",
    "多程": "Multi-leg",
    "查看详情": "View Details",
    "间数": "Rooms",
    "每间人数": "Persons per room",
    "确认密码": "Confirm Password",
    "默认排序": "Default Sort",
    "审批列表": "Approval List",
    "因公出行": "Business Trip",
    "合计金额": "Total Amount",
    "预订人员": "Booker",
    "服务费用": "Service Fee",
    "如何注销账户？": "How to Delete My Account?",
    "此账户用于登录FCM商旅预订一站式平台（包括PC端、H5和APP端）。注销前，请务必确认该账号下是否还有未使用的服务，包括行程、出差申请单、报销单。注销后，原账号下所有订单将不再可见，请慎重。": "This account is used to log in to the FCM Business Travel Booking Platform (including PC, H5, and APP). Before proceeding with account deletion, please ensure that there are no unused services under this account, including trips, travel requests, and reimbursement claims. After deletion, all orders under the original account will no longer be visible. Please proceed with caution.",
    '如果确认需要注销，请通过邮箱联系客服团队操作，联系方式详见侧栏菜单底部，或点击"呼叫客服"，与我们的服务团队通话。收到您的申请后，我们将于迟不超过十个工作日为您注销账号。': 'If you confirm that you need to delete your account, please contact our customer service team via email. The contact information can be found at the bottom of the sidebar menu, or you can click "Call Customer Service" to speak with our support team. Upon receiving your request, we will process your account deletion within a maximum of ten business days.',
    "注销账户说明": "Account Deletion Notice",
    "请选择日期": "Select date",
    "请选择出生日期": "Please select birthday",
    "审批记录": "Approval Record",
    "已选": "Selected",
    "所选日期为当地日期": "The selected date is local date",
    "未上传附件": "No attachment uploaded",
    "以上": "Above",
    "多程": "Multi-city",
    "同意并登录": "Agree and Login", 
    "需与证件一致": "Must be consistent with ID",
    "违背席别限制": "Violate Seat Class Restriction",
    "违背星级限制": "Violation of Star Rating Restriction",
    "违背最低价限制": "Violation of Lowest Price Restriction",
    "违背提前天数限制": "Violation of Advance Booking Restriction",
    "违背折扣限制": "Violation of Discount Restriction",
    "重置密码": "Reset Password",
    "请选择原因": "Please select reason",
    "乘车人、证件号码为关键信息,如因错误信息发生后续费用将由您自行承担": "Please ensure that the passenger name and ID information are accurate. Any errors and resulting costs will be the traveler's responsibility.",
    "乘机人、证件号码为关键信息,如因错误信息发生后续费用将由您自行承担": "Please ensure that the passenger name and ID information are accurate. Any errors and resulting costs will be the traveler's responsibility.",
    "密码长度为 8-32 位，且须同时包含数字、大写字母、小写字母、符号。": "Password length is 8-32 characters and must contain numbers, uppercase letters, lowercase letters, and symbols.",

    "其他机型": "Other Flight",
    "去程常客卡": "Outbound Traveler Card",
    "回程常客卡": "Inbound Traveler Card",
    '出差日期：{{noun}}': 'Travel Date: {{noun}}',
    "出差人员：{{noun}}": "Traveler: {{noun}}",
    "出差原因：{{noun}}": "Trave Reason: {{noun}}",
    "出差城市：{{noun}}": "Travel City: {{noun}}",
    "新增临客": "Add Guset",
    "出发最早": "Earliest", 
    "耗时最短": "Shortest",
    "临客": "Guset",
    "员工":"Employees",
    '从文件夹上传': 'Upload from folder',
    '打开相册或相机': 'Upload from phone album',
    "复兴号": "Renault",
    "智能动车": "Smart Train",
    "动感号": "Eco Train",
    "《火车购票服务》": "《Train ticket purchasing service》",
    '国内机票': 'Domestic Flight',
    '¥1000以上': '¥1000+',
    "房间详情": "Room Details",
    "有效申请单": "Valid Request",
    "无效申请单": "Invalid Request",
    "清空": "Clear",
    "退票": "Refund",
    "改签": "Change",
    "协议": "Corp",
    "14:00后入住": "Check-in after 14:00",
    "12:00前离店": "Check-out before 12:00",
    "新建":'New consolidated order',
    "选择差标及审批流": "Select policy and approval workflow",
    '大型': 'Large',
    '小型': 'Small',
    '中型': 'Medium',
    '快速列车': 'K-Fast',
    '高速动车组': 'high-speed EMU',
    '城际列车':'inter-city Train',
    '直达特快列车':'Intercity train',
    '特快列车':'Direct express train',
    '动车组':'EMU',
    '车组类型':'Train Type',
    '车次类型':'Vehicle Type',
    '席别类型':'Seat Type',
    '出发时段':'Departure Time',
    '到达时段':'Arrival time',
    '其他车组':'Others',
    "0-8点":'0-8am',
    "8-12点":'8-12am',
    "12-18点":'12-18pm',
    "18-24点":"18-24pm",
    "没有符合条件的车次啦~": "There are no train numbers that meet the criteria~",
    "改签行程":'Change Trip',
    '银联快捷支付':'UnionPay Quick Payment',
    '银联微信支付':'UnionPay WeChat Pay',
    '银联支付宝':'UnionPay Alipay', 
    "（超标）": "out of policy",
    "阅读并确认": "I Agree",
    "信用卡": "Credit Card",
    "添加信用卡": "Add Credit Card",
    "您还未添加授权人": "You have not added an approval officer",
    "城市景点": "City Attractions",
    "添加邮箱": "Add Email",
    "选择邮箱": "Select Email",
    "本次行程需要审批": "I need approval for this trip",
    "协议酒店": "Corporate agreement",
    "协议价":"Agreement price",
    '设置审批授权人，可以代替您审批':"To set an approval authority, who can approve on your behalf",
    '审批授权人':'Approval authority',
    '知会人':'Person to be notified',
    '如需填写多个邮箱，请使分号 “;” 隔开':'Separate multiple emails with ";"',
    "请选择舱位": "Please select cabin",
    "请上传附件": "Please Uploading attachments",
    "联系人邮箱不能为空": "The contact Email cannot be empty",
    "国际机票:不限": "International air tickets： Unlimited",
    "国内火车票:不限": "Domestic train tickets： Unlimited",
    "国内酒店:不限": "Domestic hotels： Unlimited",
    "国际酒店:不限": "International hotels： Unlimited",
    "请填写审批人邮箱":"Please input the approver's email address",
    "请输入审批人邮箱":"Please input the approver's email address",
    "请输入正确的手机号":"Please input correct phone number",
    "邮箱绑定多个账号，请重新输入账号": "Please input the correct account",
    "预付":"Pre-paid",
    "到付":"Pay at hotel",
    "请输入同意原因":"Please input the reason for approval",
    "综合订单列表": "Bundled Orders",
    "英文姓必须是英文字符":"English last name must be English characters",
    "英文名必须是英文字符":"English first name must be English characters",
    "所选日期为酒店当地日期":"The selected date is hotel local date",
    "一间房最多住两人":"One room can accommodate up to two people",
    "不允许退改":"No refunds or changes permitted",
    "无免费行李":"No free checked baggage",
    "支付列表":"Payment list ",
    "出差单":"Travel Application",
    "消息通知":"Notification",
    "立即支付":"Pay now",
    "取消支付":"Cancel payment",
    "您还未完成订单支付，如现在退出，可稍后进入【支付列表】页完成支付。确认退出吗": "You haven’t finished the payment yet. If exit now, you can go to <Payment list> Pending payment to finish the payment. Are you sure to exit now",
    "确定要取消支付吗？":"Are you sure to cancel payment?",
    "取消支付成功":"Cancel payment successfully",
    "乘客姓名/航班号/订单号": "Name of passenger/flight number/order numbe",
    "支付截至时间": "Payment deadline",
    "支付完成": "Payment completed",
    "为您推荐": "Recommended for you",
    "确认取消订单?":"Are you sure to cancel order?",
    "往返程一起订价格更优惠!":"Book round-trip together for a better price!",
    "全部已读":"All read",
    ">>>查看详情":">>>View details",
    ">>>立即支付":">>>Pay now",
    "没有未读消息":"No unread messages",
    "标记已读":"Mark as read",
    "标记未读":"Mark as unread",
    "标记成功":"Mark successfully",
    "消息详情":"Message details",
    "更新个人信用卡": "Update Personal Credit Card",
    "如勾选更新个人信用卡，则您输入的信用卡号将会被更新至您的个人信用卡。":"If you check the option to update personal credit card, the credit card number you entered will be synchronized and updated to your personal credit card account.",
    "编辑信用卡":"Edit Credit Card",
    "非本人信用卡":"Other's credit card",
    "保存成功":"Save Successful",
    "信用卡信息未变更":"Credit card information unchanged",
    "保存信用卡失败":"Failed to save credit card",
    "车票仅允许进行一次改签；\n距票面乘车站开车前48小时以上改签时，或开车前不足48小时改签票面乘车日期及以前的列车时，以及开车后在当日24时之前改签当日其他列车时，均不收改签费；\n开车前24小时以上、不足48小时，改签票面乘车日期之后的列车时，按改签前后低票价车票票面价格的5%计；\n开车前不足24小时，改签票面乘车日期之后的列车时，按改签前后低票价车票票面价格的15%计；\n开车后在当日24时之前，改签次日及以后列车时，按改签前后低票价车票票面价格的40%计。\n上述计算的尾数以5角为单位，尾数小于2.5角的舍去、2.5角（含）以上且小于7.5角的计为5角、7.5角（含）以上的进为1元。":
    "12306.cn ticket change rules (exclude Guangzhou-Shenzhen-Hongkong cross-boarder Express):\nPassengers can change the ticket once;\nNo fees apply for changes made over 48 hours before departure or changes made 24 to 48 hours before departure if switching to a train departing before 24:00 of the departure date. Additionally,changes made after the train departs for switching to a same-day train are exempt from fees;\n5% of the lower fare for changes made 24 to 48 hours before departure to a train departing later than the original date;\n15% of the lower fare for changes made less than 24 hours before departure to a train departing later than the original date;\n40% of the lower fare for changes to a next-day (or later) train after the train departs;\nThe above calculated change fee shall be rounded up to RMB 0.5, with the value less than RMB 0.25 rounded off, that more than RMB 0.25 (inclusive) and less than RMB 0.75 taken as RMB 0.5, and value more than RMB 0.75 (inclusive) rounded to RMB 1.",
    "12306广深港跨境列车退票费用标准：\n改签后的车票不得退票;\n办理退票应不晚于车票指定的日期、车次开车前30分钟，但发站为香港西九龙站的车票应不晚于45分钟;\n在车票开车时间前48小时内办理退票的，按车票票价的50%计算；\n在车票开车时间前48小时至第7天的，按车票票价的30%计算；\n在车票开车时间前8天及以上的，按车票票价的5%计算;退票费按元计算，不足一元的部分舍去免收;":
    "12306.cn Guangzhou-Shenzhen-Hongkong cross-boarder express refund rules:\nThe changed tickets can't be refunded;\nThe ticket refund should be done no later than 30 minutes before departure of the train; However, for the tickets departing from Hong Kong West Kowloon the refund should be done no later than 45 minutes before departure of the train;\n50% of the ticket price is charged if the ticket is refunded within 48 hours before departure;\n30% of the ticket price is charged if the ticket is refunded between 48 hours and 7 days before departure;\n5% of the ticket price is charged if the ticket is refunded more than 8 days (inclusive) before departure;\nThe above refund fee is calculated in RMB, with the value less than RMB 1 will be rounded off.",
    "该价格须以会员身份入住才可积分。请在入住时将会员信息提供给酒店，具体积分规则以酒店确认为准。":"Points accrual requires member check-in. Present membership details at check-in. Final allocation subject to hotel verification.",
    "积分规则":"Points Policy",
    "该价格可积分。请在预定时填写会员号，并在入住时将会员信息提供给酒店，具体积分规则以酒店确认为准。":"Points applicable to this rate. Enter membership number at booking and present membership details at check-in. Final accrual subject to hotel verification.",
    "收件邮箱:":"Recipient Email:",
    '填写正确邮箱，且只能填写一个邮箱':'Please input correct email address and only one email address',
    '请选择未预订折扣舱位的原因':'Please select the reason for unbooked discount cabin',
    "选择发票抬头": "Select invoice header",
    "级审批人": "st Approver",
    "请选择审批人":"Please select approver",
    "选择审批人":"Select Approver",
    "不允许退票": "No refunds permitted",
    "不允许改签": "No changes permitted",
    "英文姓不能为空":"English last name cannot be empty",
    "英文名不能为空":"English first name cannot be empty",
    "入住信息":"Check-in Information",
    "添加入住人":"Add check-in person",
    "选择合住人":"Select accompanying person",
    "合住不能超过两人":"Accompanying person cannot exceed two",
    "请选择未预订指定舱位的原因":"Please select the reason for unbooked specified cabin",
    "没有为其他员工预订的权限":"No permission to book for other employees",
    "入住人未选完":"There are still check-in people not selected",
    "舱位限制":"Cabin Restrictions",
    "退改规则以航司为准":"Ticket change and refund rules are subject to the airline's regulations.",
    "请填写电子行程单的邮箱":"Please fill in the email address for E-Itinerary Invoice",
    "超标弹窗提示":"Exceeded speed limit warning",
    "违背席别限制":"Violate seat class restriction",
    "行李额以航司为准":"Check-in/Carry-on luggage is subject to the airline.",
    "您确定要取消此订单吗？此操作不可撤销。":"Are you sure you want to cancel this order? This action cannot be undone.",
    "添加其他产品":"Add Other Products",
    "订单操作":"Order Actions",
    "违背":"Out of policy",
    "违背政策详情":"Out of policy",
    "超标审批":"Approval required for exceeding budget",
    "超标弹窗提示":"Pop-up prompt for exceeding limit",
    "超标自选审批或现付":"Exceed standard self-selection approval or pay on demand",
    "差旅预订前，请问您是否已经维护好您的个人信息？":"Before booking a travel, do you have completed your personal information?",
    "您使用的密码已超过90天，为保障账户信息安全，请及时修改！":"Your password has been used for more than 90 days. Please change the password to secure your account.",
    "可积分":"Points eligible",
    "不可积分":"Points ineligible",
    "每间房最多可入住 2 位客人，您当前选择的总人数与房间数量不匹配，请重新选择需预订的房间数量。": "Each room can accommodate max 2 guests. The total number of guests you currently selected does not match the number of rooms. Please reselect the number of rooms to book.",
    "每间房如 2 人入住，需在订单提交页完善每间房 2 位入住人的信息。":"2 guests per room: Complete the information of 2 occupants per room before submitting the order.",
    "您选择了2 人一间的房间，为顺利提交订单和入住，请在提交预订前完善每间房的同住人信息，确保信息与实际入住人完全一致。":"You’ve selected 2-person room. To submit your order smoothly, please complete co-occupant info for each room first. Ensure it matches the actual occupants.",
    "更多操作":"More",
    "每间房至少有一位出行人，如果出行人已选完，可删除重新选择":"Each room must have at least one traveler. If all travelers are selected, you can remove them and select again.",
    "未配置有效审批人":"No effective approver is configured",
    "支持最多 4 个邮箱，需用英文分号（;）分隔":"Up to 4 emails supported, separated by English semicolon (;)",
    "联系人邮箱最多维护4个":"Up to 4 emails supported",
    "大陆居民往来台湾通行证": "Mainland Resident Travel permit to Taiwan",
    "税费":'Taxes and Fees',
    "描述：":"Description:",
    "每日价格":"Price calendar",
    "请输入信用卡CVV：":"Please enter credit card CVV:",
    "CVV验证":"CVV Verification",
    "CVV不能为空":"CVV cannot be empty",
    "填写CVV":"Fill in CVV",
    "(含税)":"(Tax Incl)",
    "信用卡预付":"Credit card prepayment",
    "选择其他酒店或线下联系客服差旅顾问":"Select an alternative hotel or contact the FCM travel consultant offline",
    "最优票价":"Standard",
    "灵活退改":"More flexible",
    "更多行李":"More luggage",
    "更多价格":"More prices",
    "取消酒店订单将扣除全部或部分房费，最终以与酒店确认的金额为准。请留意关注您所预定酒店的取消条款。":"Cancellation of a hotel reservation may incur a deduction of all or part of the room rate, with the amount to be deducted subject to the hotel's final confirmation. Kindly ensure that you review the relevant cancellation terms applicable to your reserved hotel.",
    "无更优价格":"No better price",
    "暂无更优价格":"No better price",
    "证件有效期不能为空":"The validity of the Certificate cannot be empty",
    "{{noun}}出生日期不能为空":"The date of birth of {{noun}} cannot be empty",
    "提前付款":"Advance Payment",
    "\n*改期手续费一旦支付，航司不予退还":"*The rebooking fee shall not be refunded by the airline once payment is made.",
    "退出关联账号":"Exit associated account",
    "英文姓只能包含字母":"English surname can only contain letters",
    "英文名只能包含字母":"English name can only contain letters",
    "英文名称只能包含字母":"English name can only contain letters",
    "本页面展示的协议房型及价格仅供参考，如遇大型展会、赛事或活动期间，价格可能无法适用，最终价格及房态以酒店确认为准。":"The room category and rate displayed on this page are for reference only, it may not be available during major exhibitions, events, or activities which shall subject to change per hotel’s confirmation.",
    "暂无预订权限，请联系差旅顾问":"No booking permission, please contact the FCM travel consultant.",
    "城市住宿标准":"City Accommodation Standard",
    "当前航班无有效价格，请选择其他航班":"No valid prices available for this flight, please choose other flights.",
    "选座不等于值机，最终座位以实际值机结果为准。\n每位旅客、每个航段，仅可选择 1 个座位。\n需先选择航段与旅客，再进行座位选择。\n已确认或未确认的座位，需先取消后，方可重新选座。":
    "Seat selection does not equal to check-in, the final seat assignment is subject to the actual check-in result.\nEach traveler can only select 1 seat for each flight segment.\nPlease select the flight segment and traveler before selecting seats.\nFor confirmed or unconfirmed seats, you need to cancel first before re-selecting seats.",
    "选座":"Seat Selection",
    "航班选座须知":"Flight Seat Selection Notice",
    "取消选座":"Cancel Seat Selection",
    "确认座位":"Confirm Seat",
    "请选择座位":"Please select a seat",
    "可选":"Available",
    "不可选":"Unavailable",
    "已确认":"Confirmed",
    "同行人已选座":"Seat selected by companion",
    "未选座":"No seat selected",
    "已选座":"Seat selected",
    "待确认":"Pending confirmation",
    "取消座位成功":"Seat canceled successfully",
    "提示":"Notice",
    "您已选定座位，如需更换，请先取消当前座位再重新选择。":"You have already selected a seat. To change it, please cancel the current seat first and then select again.",
    "当前航段无法选座":"Current flight segment is not available for seat selection.",
    "紧急出口":"Exit",

}  
