# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
target 'RN0725Project' do
  config = use_native_modules!
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RCTAlipay', :path => '../node_modules/@0x5e/react-native-alipay/ios'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RN0725ProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        if ['RCTAlipay', 'RCTWeChat'].include?(target.name)
          config.build_settings['EXCLUDED_SOURCE_FILE_NAMES[sdk=iphonesimulator*]'] = '*'
        end
      end
    end

    pods_support_files_dir = File.join(installer.sandbox.root.to_s, 'Target Support Files', 'Pods-RN0725Project')
    ['debug', 'release'].each do |config_name|
      xcconfig_path = File.join(pods_support_files_dir, "Pods-RN0725Project.#{config_name}.xcconfig")
      next unless File.exist?(xcconfig_path)

      contents = File.read(xcconfig_path)
      other_ldflags_line = contents.lines.find { |l| l.start_with?('OTHER_LDFLAGS =') }
      next unless other_ldflags_line

      base_ldflags_value = other_ldflags_line.sub('OTHER_LDFLAGS =', '').strip
      sim_ldflags_value =
        base_ldflags_value
          .gsub(/-l"AlipaySDK"\s*/, '')
          .gsub(/-l"RCTAlipay"\s*/, '')
          .gsub(/-l"WeChatSDK"\s*/, '')
          .gsub(/-l"RCTWeChat"\s*/, '')
          .strip

      contents = contents
        .lines
        .reject { |l| l.start_with?('OTHER_LDFLAGS') }
        .join
        .rstrip + "\n" +
        "OTHER_LDFLAGS = $(inherited)\n" +
        "OTHER_LDFLAGS[sdk=iphoneos*] = #{base_ldflags_value}\n" +
        "OTHER_LDFLAGS[sdk=iphonesimulator*] = #{sim_ldflags_value}\n"

      File.write(xcconfig_path, contents)
    end
  end
end
